services:
  your_react_project_name:
    container_name: your_react_project_name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code
      - node_modules_volume:/app/node_modules
    # start with npm
    command: sh -c "npm start"
    ports:
      - "8080:8080"
    # enable to Hotreload
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
~
